tap 'hashicorp/tap'

brew 'macvim'
brew 'the_silver_searcher'
brew 'ripgrep'
brew 'rbenv'
brew 'hashicorp/tap/terraform'
brew 'awscli'
brew 'gh'

cask 'iterm2'
cask 'font-hack'
cask 'slack'
cask 'chatgpt'
cask 'codex-app'
cask 'claude'
cask 'claude-code'
cask 'spotify'
